### ISSUE TITLE
`on_references_result` example

### ISSUE THREAD

**Issue by olimorris** [KostkaBrukowa/definition-or-references.nvim#1]
Firstly, love the plugin. I'm reluctant to add many plugins these days as they're nearly always bloat or mask in built vim functionality. But this is too convenient 😄 .

In your wiki example, the Telescope example is heavy! I ended up using:

```
require("telescope.builtin").lsp_references({
  layout_strategy = "center",
  bufnr = 0,
})
```

Might be useful to show this to others as well.

**Comment by KostkaBrukowa** [comment]
Hmm... I'm not sure if I would put it as it is. The problem with this snippet is that `require("telescope.builtin").lsp_references` actually runs `textDocument/references` one more time (https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/__lsp.lua#L19) - being a bit slower than the example in the wiki.

But I think I can put simple and more complex example in the wiki. The simple example would be just 
```lua
local function handle_references_response(result)
  require("telescope.pickers")
    .new({}, {
      prompt_title = "LSP References",
      finder = require("telescope.finders").new_table({
        results = vim.lsp.util.locations_to_items(result, "utf-16"),
        entry_maker = require("telescope.make_entry").gen_from_quickfix(),
      }),
      previewer = require("telescope.config").values.qflist_previewer({}),
    })
    :find()
end
```
